[package]
edition = "2024"
license = { workspace = true }
name = "buck2_resource_control"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }


allocative = { workspace = true }
dupe = { workspace = true }

buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_events = { workspace = true }
buck2_util = { workspace = true }

tempfile = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fbcode_build)"] }
