[package]
edition = "2024"
license = { workspace = true }
name = "buck2_health_check"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
buck2_common = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_grpc = { workspace = true }
buck2_health_check_proto = { workspace = true }
buck2_util = { workspace = true }
dupe = { workspace = true }
itertools = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fbcode_build)'] }
